org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=false

minecraft_version=1.21.1
neo_version=21.1.251
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
sqlite_version=3.53.4.0
mod_id=litemfinder
mod_name=LItem Finder
mod_license=GPL-3.0
